### ISSUE TITLE
Restructure Client Libraries to support Dependency Injection (DI)

### ISSUE THREAD

**Issue by acupofjose** [supabase-community/supabase-csharp#35]
In reference to #23:
- [x] supabase-community/gotrue-csharp#42
- [x] supabase-community/functions-csharp#1
- [x] supabase-community/storage-csharp#2
- [x] supabase-community/realtime-csharp#16
- [x] supabase-community/postgrest-csharp#53
